name: Deploy KDoc

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create KDoc
        run: ./gradlew dokkaHtml
      - name: Deploy KDoc
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: KDoc
          folder: build/dokka/html

